#!/bin/sh

LIB_DIR="$HOME/lib"
LIB_VER="1.0.0-SNAPSHOT"
LIB_NAME="json-tools-${LIB_VER}-jar-with-dependencies.jar"

exec java -cp "${LIB_DIR}/${LIB_NAME}" com.amlinv.json.util.JsonFullUnifiedDiff "$@"
